#!/usr/bin/env python

import argparse
import requests
import boto3
import re
import sys

class elb_instances:
    def __init__(self, **kwargs):
        self.__debug = kwargs['debug']
        self.__elb = kwargs['load_balancer_name']
        self.__exclude = kwargs['exclude']

        session = boto3.session.Session(
                profile_name=kwargs['profile'],
                region_name=kwargs['region']
                )

        self.__elb_client = session.client('elb')
        self.__ec2_client = session.client('ec2')

        self.__elbs = {}
        self.__instances = {}
        self.__flags = {}
        if kwargs['flags']:
            self.__convert_flags(kwargs['flags'])

        self.out_status = 0
        self.out_msg = 'ELB: in good state'

        self.get_elbs()
        self.get_instances()
        self.compare_zones()

    def __convert_flags(self, string):
        '''
        Convert flag string to a hash.
        '''
        for flag in string.split(','):
            self.__flags[flag.split('#')[0]] = flag.split('#')[1]

    def __print(self, string, level=1):
        '''
        Simple "print" wrapper: sends to stdout if debug is > 0
        '''
        if level <= self.__debug:
            print string

    def get_instances(self):
        '''
        Get all instances in order to compare with ELBs.
        We get all instances in order to avoid AWS API limits.
        '''
        self.__print('Getting all instances')
        instances = self.__ec2_client.describe_instances()
        for reservation in instances['Reservations']:
            for instance in reservation['Instances']:
                self.__print(
                        'Instance: %s, AZ: %s' % (
                            instance['InstanceId'],
                            instance['Placement']['AvailabilityZone']
                            ),
                        2
                        )
                self.__instances[instance['InstanceId']] = {
                    'availability': instance['Placement']['AvailabilityZone'],
                    }

    def __get_flag(self, flag):
        '''
        Get remote flags and returns its content
        '''
        try:
            rep = requests.get(flag)
        except requests.exceptions.ConnectionError:
            self.__print('ConnectionError for %s' % flag)
            return False
        if rep.status_code == '200':
            self.__print('Flag %s contains %s' % (flag, rep.text), 2)
            return rep.text
        self.__print('Flag %s returned %i' % (flag, rep.status_code))
        return False

    def get_elbs(self):
        '''
        Either get all ELBs, exclude some, or just get one, depending on script invocation.
        '''
        if self.__elb == 'all':
            self.__print('Getting all ELBs')
            lbs = self.__elb_client.describe_load_balancers()
        else:
            self.__print('Getting only %s' % self.__elb)
            lbs = self.__elb_client.describe_load_balancers(
                    LoadBalancerNames = [self.__elb]
                    )

        for lb in lbs['LoadBalancerDescriptions']:
            self.__print(
                    'ELB name: %s, AZ: %s' % (
                        lb['LoadBalancerName'], ', '.join(lb['AvailabilityZones'])
                        ),
                    2
                    )
            ignore = False
            if lb['LoadBalancerName'] in self.__flags:
                dflag = self.__get_flag(self.__flags[lb['LoadBalancerName']])
                if dflag and dflag != 'active':
                    ignore = True


            if self.__exclude and re.match(self.__exclude,lb['LoadBalancerName']):
                self.__print('ignoring ELB %s because it matches exclude regex' % lb['LoadBalancerName'])
            elif ignore:
                self.__print('ignoring ELB %s because it is deactivated by remote flag' % lb['LoadBalancerName'])
            else:
                attributes = self.__elb_client.describe_load_balancer_attributes(
                        LoadBalancerName = lb['LoadBalancerName']
                        )
                instance_health = self.__elb_client.describe_instance_health(
                        LoadBalancerName = lb['LoadBalancerName']
                        )
                health = {}
                for ih in instance_health['InstanceStates']:
                    health[ih['InstanceId']] = ih['State']
                self.__elbs[lb['LoadBalancerName']] = {
                        'availability': lb['AvailabilityZones'],
                        'cross': attributes['LoadBalancerAttributes']['CrossZoneLoadBalancing']['Enabled'],
                        'health': health,
                        }

    def compare_zones(self):
        '''
        Get ELBs activated AZ, and check each of them has at least one instance.
        Also ensure instances are properly working.
        '''
        for elb in self.__elbs:
            if len(self.__elbs[elb]['health']) > 0:
                for instance in self.__elbs[elb]['health']:
                    if self.__instances[instance]['availability'] not in self.__elbs[elb]['availability']:
                        self.__print(
                                'Instance %s (%s) not in activated AZ for %s (%s)' %(
                                    instance, self.__instances[instance]['availability'], elb, ', '.join(self.__elbs[elb]['availability'])
                                    ),
                                1
                                )
                        if self.out_status == 0:
                            self.out_status = 1
                            self.out_msg = 'At least one instance not in use'
                    else:
                        if self.__elbs[elb]['health'][instance] == 'InService':
                            self.__print(
                                    'Found %s for %s, state: %s' % (
                                        instance, elb, 'InService'
                                        ),
                                    2
                                    )
                        else:
                            self.__print(
                                    'Found %s for %s, state: %s' % (
                                        instance, elb, self.__elbs[elb]['health'][instance]
                                        ),
                                    1
                                    )
                            self.out_status = 2
                            self.out_msg = 'At least one instance out of ELB'
            else:
                self.__print('ELB %s has no instance'%elb, 1)
                self.out_status = 2
                self.out_msg = 'At least one ELB has no instance'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Check attached instances for each (or given) ELB')
    parser.add_argument('--debug',  '-d',   help='Set verbosity level', default=0, type=int)
    parser.add_argument('--load-balancer-name', '-e',   help='Check only this ELB', default='all')
    parser.add_argument('--profile', '-p', help='Pass AWS profile name', default='default')
    parser.add_argument('--region', '-r',   help='Set AWS region', default='eu-west-1')
    parser.add_argument('--exclude', '-x',   help='Exclude ELB if its name matches regex', default=False)
    parser.add_argument('--remote-flags', '-R', help='Remote flag for specific ELbs, in the form elb-name#remoteflag,elbname#remoteflag,...', type=str)
    args = parser.parse_args()

    worker = elb_instances(
            debug = args.debug,
            load_balancer_name = args.load_balancer_name,
            profile = args.profile,
            region = args.region,
            exclude = args.exclude,
            flags = args.remote_flags
            )
    print worker.out_msg
    sys.exit(worker.out_status)
